package net.sf.seesea.rendering.chart.editpart;

import java.util.HashMap;
import java.util.Map;

public class MMSI {

	public static String getCountry(long mmsi) {
		String mms = Long.toString(mmsi);
		String countrycode = mms.substring(0, 3);
		Map<String, String> countries = new HashMap<String, String>();
		countries.put("201","Albania");
		countries.put("278","Slovenia");
		countries.put("202","Andorra");
		countries.put("203","Austria");
		countries.put("204","Azores");
		countries.put("205","Belgium");
		countries.put("206","Belarus");
		countries.put("207","Bulgaria");
		countries.put("208","Vatican");
		countries.put("209","Cyprus");
		countries.put("210","Cyprus");
		countries.put("211","Germany");
		countries.put("212","Cyprus");
		countries.put("213","Georgia");
		countries.put("214","Moldova");
		countries.put("215","Malta");
		countries.put("216","Armenia");
		countries.put("217","");
		countries.put("218","Germany");
		countries.put("219","Denmark");
		countries.put("220","Denmark");
		countries.put("221","");
		countries.put("222","");
		countries.put("223","");
		countries.put("224","Spain");
		countries.put("225","Spain");
		countries.put("226","France");
		countries.put("227","France");
		countries.put("228","France");
		countries.put("230","Finland");
		countries.put("231","");
		countries.put("232","United Kingdom");
		countries.put("233","United Kingdom");
		countries.put("234","United Kingdom");
		countries.put("235","United Kingdom");
		countries.put("236","Gibraltar");
		countries.put("237","Greece");
		countries.put("238","Croatia");
		countries.put("239","Greece");
		countries.put("240","Greece");
		countries.put("242","Morocco");
		countries.put("243","Hungary");
		countries.put("244","Netherlands");
		countries.put("245","Netherlands");
		countries.put("246","Netherlands");
		countries.put("247","Italy");
		countries.put("248","Malta");
		countries.put("249","Malta");
		countries.put("250","Ireland");
		countries.put("251","Iceland");
		countries.put("252","Liechtenstein");
		countries.put("253","Luxembourg");
		countries.put("254","Monaco");
		countries.put("255","Madeira");
		countries.put("256","Malta");
		countries.put("257","Norway");
		countries.put("258","Norway");
		countries.put("259","Norway");
		countries.put("261","Poland");
		countries.put("262","Montenegro");
		countries.put("263","Portugal");
		countries.put("264","Romania");
		countries.put("265","Sweden");
		countries.put("266","Sweden");
		countries.put("267","Slovak Republic");
		countries.put("268","San Marino");
		countries.put("269","Switzerland");
		countries.put("270","Czech Republic");
		countries.put("271","Turkey");
		countries.put("272","Ukraine");
		countries.put("273","Russian Federation");
		countries.put("274","Macedonia");
		countries.put("275","Latvia");
		countries.put("276","Estonia");
		countries.put("277","Lithuania");
		countries.put("279","Serbia");
		countries.put("301","Anguilla");
		countries.put("303","Alaska");
		countries.put("304","Antigua and Barbuda");
		countries.put("305","Antigua and Barbuda");
		countries.put("306","Netherlands Antilles");
		countries.put("307","Aruba");
		countries.put("308","Bahamas");
		countries.put("309","Bahamas");
		countries.put("310","Bermuda");
		countries.put("311","Bahamas");
		countries.put("312","Belize");
		countries.put("314","Barbados");
		countries.put("316","Canada");
		countries.put("319","Cayman Islands");
		countries.put("321","Costa Rica");
		countries.put("323","Cuba");
		countries.put("325","Dominica");
		countries.put("327","Dominican Republic");
		countries.put("329","Guadeloupe");
		countries.put("330","Grenada");
		countries.put("331","Greenland");
		countries.put("332","Guatemala");
		countries.put("334","Honduras");
		countries.put("336","Haiti");
		countries.put("338","USA");
		countries.put("339","Jamaica");
		countries.put("341","");
		countries.put("343","Saint Lucia");
		countries.put("345","Mexico");
		countries.put("347","Martinique");
		countries.put("348","Montserrat");
		countries.put("350","Nicaragua");
		countries.put("351","Panama");
		countries.put("352","Panama");
		countries.put("353","Panama");
		countries.put("354","Panama");
		countries.put("358","Puerto Rico");
		countries.put("359","El Salvador");
		countries.put("362","Trinidad and Tobago");
		countries.put("366","USA");
		countries.put("367","USA");
		countries.put("368","USA");
		countries.put("369","USA");
		countries.put("371","Panama");
		countries.put("372","Panama");
		countries.put("375","Saint Vincent");
		countries.put("376","Saint Vincent");
		countries.put("377","Saint Vincent");
		countries.put("378","British Virgin Islands");
		countries.put("379","United States Virgin Islands");
		countries.put("400","Afghanistan");
		countries.put("403","Saudi Arabia");
		countries.put("405","Bangladesh");
		countries.put("408","Bahrain");
		countries.put("410","Bhutan");
		countries.put("412","China");
		countries.put("413","China");
		countries.put("416","Taiwan");
		countries.put("419","India");
		countries.put("422","Iran");
		countries.put("425","Iraq");
		countries.put("428","Israel");
		countries.put("431","Japan");
		countries.put("432","Japan");
		countries.put("434","Turkmenistan");
		countries.put("437","Uzbekistan");
		countries.put("438","Jordan");
		countries.put("440","Korea");
		countries.put("441","Korea");
		countries.put("443","Palestine");
		countries.put("445","No. Korea");
		countries.put("447","Kuwait");
		countries.put("450","Lebanon");
		countries.put("453","Macao");
		countries.put("455","Maldives");
		countries.put("457","Mongolia");
		countries.put("459","Nepal");
		countries.put("461","Oman");
		countries.put("463","Pakistan");
		countries.put("466","Qatar");
		countries.put("468","Syrian Arab Republic");
		countries.put("470","United Arab Emirates");
		countries.put("473","Yemen");
		countries.put("475","Yemen");
		countries.put("477","Hong Kong");
		countries.put("478","Bosnia and Herzegovina");
		countries.put("503","Australia");
		countries.put("506","Myanmar");
		countries.put("510","Micronesia");
		countries.put("512","New Zealand");
		countries.put("514","Cambodia");
		countries.put("515","Cambodia");
		countries.put("516","Christmas Island");
		countries.put("518","Cook Islands");
		countries.put("520","Fiji");
		countries.put("523","Cocos");
		countries.put("525","Indonesia");
		countries.put("529","Kiribati");
		countries.put("531","Lao People's Democratic Republic");
		countries.put("533","Malaysia");
		countries.put("536","Northern Mariana Islands");
		countries.put("538","Marshall Islands");
		countries.put("540","New Caledonia");
		countries.put("544","Nauru");
		countries.put("546","French Polynesia");
		countries.put("548","Philippines");
		countries.put("555","Pitcairn Island");
		countries.put("557","Solomon Islands");
		countries.put("559","American Samoa");
		countries.put("561","Samoa");
		countries.put("563","Singapore");
		countries.put("564","Singapore");
		countries.put("565","Singapore");
		countries.put("567","Thailand");
		countries.put("570","Tonga");
		countries.put("572","Tuvalu");
		countries.put("574","Viet Nam");
		countries.put("576","Vanuatu");
		countries.put("601","South Africa");
		countries.put("603","Angola");
		countries.put("605","Algeria");
		countries.put("607","Saint Paul and Amsterdam Islands");
		countries.put("608","Ascension Island");
		countries.put("609","Burundi");
		countries.put("610","Benin");
		countries.put("611","Botswana");
		countries.put("612","Central African Republic");
		countries.put("613","Cameroon");
		countries.put("615","Congo");
		countries.put("616","Comoros");
		countries.put("617","Cape Verde");
		countries.put("621","Djibouti");
		countries.put("622","Egypt");
		countries.put("624","Ethiopia");
		countries.put("625","Eritrea");
		countries.put("626","Gabonese Republic");
		countries.put("627","Ghana");
		countries.put("629","Gambia");
		countries.put("630","Guinea-Bissau");
		countries.put("631","Equatorial Guinea");
		countries.put("632","Guinea");
		countries.put("634","Kenya");
		countries.put("636","Liberia");
		countries.put("637","Liberia");
		countries.put("642","Libya");
		countries.put("644","Lesotho");
		countries.put("645","Mauritius");
		countries.put("647","Madagascar");
		countries.put("649","Mali");
		countries.put("650","Mozambique");
		countries.put("654","Mauritania");
		countries.put("655","Malawi");
		countries.put("656","Niger");
		countries.put("657","Nigeria");
		countries.put("659","Namibia");
		countries.put("660","Reunion");
		countries.put("661","Rwanda");
		countries.put("662","Sudan");
		countries.put("663","Senegal");
		countries.put("664","Seychelles");
		countries.put("665","Saint Helena");
		countries.put("666","Somali Democratic Republic");
		countries.put("667","Sierra Leone");
		countries.put("669","Swaziland");
		countries.put("670","Chad");
		countries.put("671","Togolese Republic");
		countries.put("672","Tunisia");
		countries.put("674","Tanzania");
		countries.put("675","Uganda");
		countries.put("676","Congo");
		countries.put("677","Tanzania");
		countries.put("678","Zambia");
		countries.put("679","Zimbabwe");
		countries.put("701","Argentina");
		countries.put("710","Brazil");
		countries.put("720","Bolivia");
		countries.put("725","Chile");
		countries.put("730","Colombia");
		countries.put("735","Ecuador");
		countries.put("740","Falkland Islands");
		countries.put("745","Guiana");
		countries.put("750","Guyana");
		countries.put("755","Paraguay");
		countries.put("760","Peru");
		countries.put("765","Suriname");
		countries.put("770","Uruguay");
		countries.put("775","Venezuela");
		return countries.get(countrycode);
	}
	
}
